@echo off

md C:\Workspace\Build 2>nul
cd /d C:\Workspace\Build

cmake -DLLVM_ENABLE_PROJECTS=clang -DLLVM_USE_CRT_DEBUG=MTd -DLLVM_USE_CRT_RELEASE=MT -DLLVM_INCLUDE_TESTS=OFF -DCLANG_INCLUDE_TESTS=OFF -DLLVM_INCLUDE_BENCHMARKS=OFF -G "Visual Studio 17 2022" -A x64 -Thost=x64 C:\Workspace\LLVM\llvm
